#Vectors in R and Python-- Alejandro Huaman / 20203800


In [ ]:
## if needed, run this and RESTART KERNEL
# import os
# os.environ['R_HOME'] ='/Library/Frameworks/R.framework/Resources'

In [ ]:
%load_ext rpy2.ipython

## 1. Creating

In [ ]:
import numpy as np

namesP=np.array(["Gloria", "Wilhelm", "Natasha", "Rafael","Harry","Sadio","Rajesh","Carlos"])
agesP=np.array([20,17,30,25,29,30,35,70])
countryP=np.array(["Perú", "Suecia", "Rusia", "Colombia","Inglaterra","Senegal","India","España"])
civil_estatusP=np.array(["Casada", "Soltero", "Soltero", "Casado","Viudo", "Casado","Soltero","Casado"])

In [ ]:
namesP

['Gloria',
 'Wilhelm',
 'Natasha',
 'Rafael',
 'Harry',
 'Sadio',
 'Rajesh',
 'Carlos']

In [ ]:
%%R
namesR=list("Gloria", "Wilhem", "Natasha", "Rafael","Harry","Sadio","Rajesh","Carlos")
agesR=list(20,17,30,25,29,30,35,70)
countryR=list("Perú", "Suecia", "Rusia", "Colombia","Inglaterra","Senegal","India","España")
civil_estatusR=list("Casada", "Soltero", "Soltero", "Casado","Viudo", "Casado","Soltero","Casado")

In [ ]:
%%R
namesR

[[1]]
[1] "Gloria"

[[2]]
[1] "Wilhem"

[[3]]
[1] "Natasha"

[[4]]
[1] "Rafael"

[[5]]
[1] "Harry"

[[6]]
[1] "Sadio"

[[7]]
[1] "Rajesh"

[[8]]
[1] "Carlos"



## 2. Accessing

In [ ]:
# Keep in mind the positions in Python start in **0**.
agesP[2]

30

In [ ]:
%%R
agesR[3]

[[1]]
[1] 30



In [ ]:
#last element
countryP[-4]

'Inglaterra'

In [ ]:
%%R
tail(countryR,2)

[[1]]
[1] "India"

[[2]]
[1] "España"



### Slices

In [ ]:
# several, using slices:
agesP[0:4] #first to fourth

[20, 17, 30, 25]

In [ ]:
%%R
agesR[1:5]

[[1]]
[1] 20

[[2]]
[1] 17

[[3]]
[1] 30

[[4]]
[1] 25

[[5]]
[1] 29



In [ ]:
# non consecutive

agesP[[1,3,5]]

array([17, 25, 30])

In [ ]:
%%R
agesR[c(2,4,6)]

[[1]]
[1] 17

[[2]]
[1] 25

[[3]]
[1] 30



## Replacing

### by Position

In [ ]:
countryP[6]="Bharat"

# list changed:
countryP

['Perú',
 'Suecia',
 'Rusia',
 'Colombia',
 'Inglaterra',
 'Senegal',
 'Bharat',
 'España']

In [ ]:
%%R
countryR[7]="Bharat"

# list changed:
countryR

[[1]]
[1] "Perú"

[[2]]
[1] "Suecia"

[[3]]
[1] "Rusia"

[[4]]
[1] "Colombia"

[[5]]
[1] "Inglaterra"

[[6]]
[1] "Senegal"

[[7]]
[1] "Bharat"

[[8]]
[1] "España"



### By Value

In [ ]:
countryP[countryP=='Perú']="Holanda"
countryP

array(['Holanda', 'Suecia', 'Rusia', 'Colombia', 'Inglaterra', 'Senegal',
       'India', 'España'], dtype='<U10')

In [ ]:
%%R
countryR[countryR=='Perú']="INCAS"
countryR

[[1]]
[1] "INCAS"

[[2]]
[1] "Suecia"

[[3]]
[1] "Rusia"

[[4]]
[1] "Colombia"

[[5]]
[1] "Inglaterra"

[[6]]
[1] "Senegal"

[[7]]
[1] "India"

[[8]]
[1] "España"



## Deleting

### By Position

In [ ]:
countryP=np.delete(countryP,-3)
countryP

array(['Perú', 'Suecia', 'Rusia', 'Colombia', 'Inglaterra', 'India',
       'España'], dtype='<U10')

In [ ]:
%%R
countryR=countryR[-length(countryR)]
countryR

[[1]]
[1] "INCAS"

[[2]]
[1] "Suecia"

[[3]]
[1] "Rusia"

[[4]]
[1] "Colombia"

[[5]]
[1] "Inglaterra"

[[6]]
[1] "Senegal"

[[7]]
[1] "India"



In [ ]:
# for several positions

vectorP=np.array([11,22,33,55,88,1313])
vectorP=np.delete(vectorP,range(3,5))
#now:
vectorP

array([  11,   22,   33, 1313])

In [ ]:
%%R

vectorR=c(20,30,40,50,60,70)
vectorR=vectorR[-c(2:4)]

#now:
vectorR

[1] 20 60 70


In [ ]:
# non consecutive
byeIndex=[1, 3, 5]

vectorP=np.array([11,22,33,44,55,66])
new_vectorP=np.delete(vectorP,byeIndex)

#now:
new_vectorP

In [ ]:
%%R
vectorR=c(11,22,33,44,55,66)
new_vectorR=vectorR[-c(2,4,6)]
new_vectorR

### by Value

In [ ]:
# by value
vectorP=np.array([25,1,2024,28,12])

vectorP=np.delete(vectorP, np.where(vectorP == 25))

#  changed:
vectorP

array([   1, 2024,   28,   12])

In [ ]:
%%R

vectorR=c(1,8,27,64,125)
vectorR=vectorR[vectorR!=64]
vectorR


[1]   1   8  27 125


In [ ]:
# by value
vectorP=np.array([2010,2014,2015,2016,2018])

#vectorP=
vectorP=np.delete(vectorP, np.isin(vectorP,[2010,2018]))

#  changed:
vectorP

array([2014, 2015, 2016])

In [ ]:
%%R

vectorR=c(8,3,5,1,4)
vectorR=vectorR[!vectorR%in%c(3,5)]
vectorR

[1] 8 1 4


## Inserting values

### at the End

In [ ]:
vectorP=np.array([39,2,3,4])
vectorP=np.append(vectorP,1)
vectorP

array([39,  2,  3,  4,  1])

In [ ]:
%%R
vectorR=c(43,56,78,91)
vectorR=c(vectorR,2014)
vectorR

[1]   43   56   78   91 2014


### in a particular location

In [ ]:
vectorP=np.array([34,54,65,98])
vectorP=np.insert(vectorP,obj=3,values=45) #obj is position
vectorP

array([34, 54, 65, 45, 98])

In [ ]:
%%R
vectorR=c(4,8,13,72)
vectorR=append(vectorR,360,after=2)
vectorR

[1]   4   8 360  13  72


## Concatenating

In [ ]:
import numpy as np

vectorP1=np.array([31,42,54,86])
vectorP2=np.array(['A','G'])
vectorP12=np.concatenate((vectorP1,vectorP2))
vectorP12

array(['31', '42', '54', '86', 'A', 'G'], dtype='<U21')

In [ ]:
%%R
vectorR1=c(4,24,64,84)
vectorR2=c('G','F')
vectorR12=c(vectorR1,vectorR2)
vectorR12

[1] "4"  "24" "64" "84" "G"  "F" 


Remember that vectors support just one data type, and coercion will activate when different data types are detected.

In [ ]:
vectorP1=np.array([23,11,78,28,"LUV"])
vectorP1

array(['23', '11', '78', '28', 'LUV'], dtype='<U21')

In [ ]:
%%R
vectorR1=c(28,12,20,"ALORIA")
vectorR1

[1] "28"     "12"     "20"     "ALORIA"
